### ISSUE TITLE
Still, version has been identified as a keyword in VSCode version 4.5.1

### ISSUE THREAD

**Issue by Thiyanwso2** [ballerina-platform/ballerina-grammar#116]
**Description:**
$subject

![Screenshot from 2023-09-19 11-57-14](https://github.com/ballerina-platform/ballerina-grammar/assets/65483741/450e1140-b90b-46cf-b953-5adb751c7440)

**Comment by anupama-pathirage** [comment]
Closing as https://github.com/wso2/ballerina-vscode/issues/554 is created to track this.
