### ISSUE TITLE
Changing the documentation, deprecated keyword color

### ISSUE THREAD

**Issue by Shan1024** [ballerina-platform/ballerina-grammar#12]
**Description:**
I think it would be better to change the color of `documentation`, `deprecated` keywords to comment color since these keywords distracts the user from going through the actual code. WDYT?

<img width="660" alt="op_codes bal 2018-06-12 07-38-36" src="https://user-images.githubusercontent.com/4003115/41266231-aa090112-6e13-11e8-8442-d9d7e72cdf65.png">

**Comment by hevayo** [comment]
Documentation syntax has changed in the language hence closing the issue.
